# Generated by Django 3.0.4 on 2020-07-11 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('class_desc', models.TextField()),
                ('start_time', models.TimeField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='classinfo',
            name='class_desc',
        ),
        migrations.RemoveField(
            model_name='classinfo',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='classinfo',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='classinfo',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='QuestionAndAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='classinfo',
            name='classname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Questions.AllClasses'),
            preserve_default=False,
        ),
    ]
