# Generated by Django 3.0.4 on 2020-07-12 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0005_auto_20200712_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionandanswers',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Questions.Answer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionandanswers',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Questions.Questions'),
            preserve_default=False,
        ),
    ]
