# Generated by Django 3.0.4 on 2020-07-12 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0006_auto_20200712_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='questions',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='questionandanswers',
            name='answer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Questions.Answer'),
        ),
    ]
