# Generated by Django 3.0.4 on 2020-07-12 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0007_auto_20200712_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionandanswers',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Questions.Answer'),
        ),
    ]
